### ISSUE TITLE
[Help] 

### ISSUE THREAD

**Issue by sk1350** [wyguo/ThreeDRNAseq#14]
**Error: need finite 'ylim' values**
I get this error when trying to plot the mean-variance trend. What does it mean? 

Also when trying to run limma it gives me this warning and error:
Warning in voom(dge, design, plot = F, span = span, ...) :
  The experimental design has no replication. Setting weights to 1.
Fit a basic linear model ...
Fit the contrast model ...
[1] "Contrast groups: T13.brep1-T16.brep1; (T10.brep1+T10.brep2)/2-(T13.brep1+T13.brep2)/2; (T13.brep1+T13.brep2)/2-(T16.brep1+T16.brep2)/2"
Fit a eBayes model ...
Warning: **Error in .ebayes: No residual degrees of freedom in linear model fits**

Does it mean I cannot use this package with only 2 reps per time point?

**Comment by wyguo** [comment]
Hi,
The 3D App can work for 2 replciates dataset. But from the error message, it seems that your dataset has no replicates. Please double check your input files according to the user manual. I guess it could be your input file problem.

**Comment by sk1350** [comment]
Hello, 
I have used a different dataset that has previously been analysed with DEXSeq. ThreeDRNASeq ran fine up until it gave out the results that stated that there were only 12 DAS genes between two conditions, which is wrong because DEXSeq gave out hundreds of DAS genes. Would you have any idea why that could be?

**Comment by wyguo** [comment]
Hi,
ThreeDRNAseq and DEXSeq are different tools and based on different methods. It is very common that they lead to different results. There are several reasons that you get small DAS gene list by using ThreeDRNAseq

1.      3D RNA-seq method has a stringent filter for the results of significance. The cut-offs are not only applied to the adjusted p-values, but also applied to the delta PS values.

2.      The reference transcriptome quality has a big inference to the transcript quantification, thereby impacting the quality of alternative splicing analysis.

3.      The RNA-seq data quality has influence to the analysis results.

**Comment by sk1350** [comment]
Thank you very much for this explanation.
