### ISSUE TITLE
[Bug] quant.genes.sf auto-selection

### ISSUE THREAD

**Issue by PeterVenhuizen** [wyguo/ThreeDRNAseq#2]
When selecting my Salmon quantification data, the 3D RNA-seq App automatically selects the quant.genes.sf file also available in the provided folders, together with the quant.sf file. (Re-)Moving the quant.genes.sf files fixes this issues, but this should be fixed in the R code

**Comment by wyguo** [comment]
> When selecting my Salmon quantification data, the 3D RNA-seq App automatically selects the quant.genes.sf file also available in the provided folders, together with the quant.sf file. (Re-)Moving the quant.genes.sf files fixes this issues, but this should be fixed in the R code

Hi,
Many thanks for the feedback. I am going to correct the bug and make improvement in the coming new version. :)

**Comment by peterjc** [comment]
Was this fixed? i.e. Can this issue be closed?

**Comment by wyguo** [comment]
Yes, thanks for your suggestions on improvement.

**Comment by peterjc** [comment]
@wyguo the issue is still open
