### ISSUE TITLE
Warning: Error in isTRUE: object 'lang' not found

### ISSUE THREAD

**Issue by huang-sh** [wyguo/ThreeDRNAseq#30]
Thanks for providing 3D RNA-seq App.

**Describe the question**
I try to run the APP with `run3DApp()`. But I get the error "object 'lang' not found".  Can you provide some help?
Thank you!

**Screenshots**

![image](https://user-images.githubusercontent.com/24741118/123104163-4dfccd80-d469-11eb-8be6-dde5076af448.png)
![browser](https://user-images.githubusercontent.com/24741118/123104188-5228eb00-d469-11eb-91c7-952c88a19d2f.png)
![image](https://user-images.githubusercontent.com/24741118/123104204-548b4500-d469-11eb-8dbc-c3340effa399.png)

**Comment by wyguo** [comment]
Hi, 
Thanks for using our App. 
I couldn't reproduce the same error . The App just work well on my PC. I don't have an exact answer. But from the error message, it seems that the error is related to the rlang package. In you R console, you can run the command library(rlang) and library(plotly) to check if these two packages are properly installed. 
Best

**Comment by huang-sh** [comment]
Hi, Thank you. Although I don't know what happen, it works when I try to run the APP in a new R session.
