### ISSUE TITLE
[Help] Loading the experimental design file

### ISSUE THREAD

**Issue by RxLoutre** [wyguo/ThreeDRNAseq#31]
Hi ! Thank you a lot for the great app. I really see it was a lot of work and I am looking forward to dive into it a bit more ! Very nice help and documentation as well.

I have recently installed all the dependencies and your package on my MacBook. It went smoothly (Only had to download X11 for Cairo to work properly and also do this manually : install.packages("cli") ). So now I am trying out threeDRNAseq locally on my laptop in RShiny. I had run several salmon analysis from the command line and I wanted to explore the result with your package.

**Describe the question**
As I keep getting the following error :  

`The quantification file names in the sample meta-table do not match to the quantification files. Please double check whether (1) the quantification file names in the metadata table match to the files in the quantification folder or (2) you have selected the correct quantification method in Step 1`

I Think I might do something wrong, and I struggle to understand what is expected of the last column of metadata file. The full path to the file on my computer? Or just the name of the folder in the archive ? I have tried both way, but both fail. I have read many times this section : https://github.com/wyguo/ThreeDRNAseq/blob/master/vignettes/user_manuals/3D_RNA-seq_App_manual.md#input-files , but I feel like I understood correctly, can't find where I am wrong. Could you please assist me ? Thank you a lot !

Roxane

**Screenshots**
![image](https://user-images.githubusercontent.com/13352219/146212647-cbb86133-50c5-4e0d-8a69-b5c61b61bad1.png)

![image](https://user-images.githubusercontent.com/13352219/146213205-6e736ff7-1663-40af-8d32-11e1bd1607f7.png)

![image](https://user-images.githubusercontent.com/13352219/146213801-10bb3ae6-54ba-4bfc-ad91-3e27d7c77d60.png)

 Archive.zip here contain all the folders. Each folder contain salmon results for one sample.
 
 
![image](https://user-images.githubusercontent.com/13352219/146217797-909e3978-b852-4356-ae7f-6ce945ee2c97.png)

**Comment by wyguo** [comment]
Hi Roxane,
Thanks for using our 3D RNA-seq App. I notice that in the last column of the metatable, you put capital letters "MK",  but the file name should be "Mk", k is in lower case. 
Best,
Wenbin

**Comment by RxLoutre** [comment]
Good morning Wenbin !

Oh that is a rookie mistake 🙈 and I have been looking for it for quite a long time as well. Thank you for pointing it out for me ! 

It is working now, great thank you a lot and have a nice day !

Best,

Roxane
