### ISSUE TITLE
[Question] Count table after normalization

### ISSUE THREAD

**Issue by RxLoutre** [wyguo/ThreeDRNAseq#32]
Hi Wenbin,

Happy new year ! First "issue" of 2022. :) 

I have an other question. Sorry if I have missed this information somewhere. I would like to know if it is possible to download something similar to the file "Gene read counts.csv", which is generated by 3D RNAseq when you press the "download" button in the result folder, but for reads **after TMM normalization.** Or maybe the reads count here are already normalized ?

Thank you for your help, have a nice day.

Best,

**Comment by wyguo** [comment]
Hi, 
Happy new year!
Unfortunately, you can’t download the “reads after TMM normalization” spreadsheet directly from the 3D RNA-seq App. But you can use R to open the object “intermediate_data.RData” in the data folder, which is generated after you click the “save data” button on the last page. It is a list object. You can get “genes_log2FC” and “trans_log2FC” from this object. Please see details in: https://github.com/wyguo/ThreeDRNAseq/blob/master/vignettes/user_manuals/3D_RNA-seq_App_manual.md#files-in-data-folder

**Comment by RxLoutre** [comment]
No problem that we can't get it from the App ! I think getting it from the .RData file should be enough for my purpose. Many thanks 🙏
